// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxD06TXTxkr8yBIfeHKOGoMTg_iBa1WcY',
    appId: '1:47012320801:web:d637134bd85cd6da0e3560',
    messagingSenderId: '47012320801',
    projectId: 'mobileprogramming-54f90',
    authDomain: 'mobileprogramming-54f90.firebaseapp.com',
    storageBucket: 'mobileprogramming-54f90.firebasestorage.app',
    measurementId: 'G-PQ5NQSTQCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN0LrCiLlDTCPG5xVlkNovYzFWvVbcXuc',
    appId: '1:47012320801:android:bbe0c1afd84ec2a20e3560',
    messagingSenderId: '47012320801',
    projectId: 'mobileprogramming-54f90',
    storageBucket: 'mobileprogramming-54f90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoRiP16PZWx-e0Z3o5bblh3KCK8jk5Bms',
    appId: '1:47012320801:ios:2a1a95860f3606530e3560',
    messagingSenderId: '47012320801',
    projectId: 'mobileprogramming-54f90',
    storageBucket: 'mobileprogramming-54f90.firebasestorage.app',
    iosClientId: '47012320801-0fvrq29ut626qkm505v4etens6eudnph.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoRiP16PZWx-e0Z3o5bblh3KCK8jk5Bms',
    appId: '1:47012320801:ios:2a1a95860f3606530e3560',
    messagingSenderId: '47012320801',
    projectId: 'mobileprogramming-54f90',
    storageBucket: 'mobileprogramming-54f90.firebasestorage.app',
    iosClientId: '47012320801-0fvrq29ut626qkm505v4etens6eudnph.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxD06TXTxkr8yBIfeHKOGoMTg_iBa1WcY',
    appId: '1:47012320801:web:71cb7d8f44b7a12a0e3560',
    messagingSenderId: '47012320801',
    projectId: 'mobileprogramming-54f90',
    authDomain: 'mobileprogramming-54f90.firebaseapp.com',
    storageBucket: 'mobileprogramming-54f90.firebasestorage.app',
    measurementId: 'G-3C38TDBKB3',
  );
}
